<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run() {
        DB::table('questions')->insert([
            [
                'enunciado' => 'Qual propriedade de css muda cor de um texto?',
                'opcao_a' => 'Background-color',
                'opcao_b' => 'Background-image',
                'opcao_c' => 'Color',
                'opcao_d' => 'Filter',
                'resposta_correta' => 'opcao_c',
                'dificuldade' => 'Fácil',
            ],
            [
                'enunciado' => 'Qual propriedade de css muda a cor de fundo de uma página?',
                'opcao_a' => 'Background-color',
                'opcao_b' => 'Background-cover',
                'opcao_c' => 'Color',
                'opcao_d' => 'Filter',
                'resposta_correta' => 'opcao_a',
                'dificuldade' => 'Médio',
            ],
            [
                'enunciado' => 'Qual propriedade de css centraliza um texto em uma div?',
                'opcao_a' => 'Text-align: center',
                'opcao_b' => 'Justify-content: space-between',
                'opcao_c' => 'Margin: center',
                'opcao_d' => 'Align-items: center',
                'resposta_correta' => 'opcao_a',
                'dificuldade' => 'Fácil',
            ],
            [
                'enunciado' => 'O que a tag <td> do HTML representa?',
                'opcao_a' => 'Linha em uma tabela',
                'opcao_b' => 'Célula de dados',
                'opcao_c' => 'Cabeçalho de uma tabela',
                'opcao_d' => 'Nenhum das anterioras',
                'resposta_correta' => 'opcao_b',
                'dificuldade' => 'Difícil',
            ],
            [
                'enunciado' => 'Qual seria a estrutura básica completa de um HTML?',
                'opcao_a' => 'html > header > head > body > main > footer',
                'opcao_b' => 'header > main > footer',
                'opcao_c' => 'html > head > body > header > main',
                'opcao_d' => 'html > head > body > header > main > footer',
                'resposta_correta' => 'opcao_d',
                'dificuldade' => 'Médio',
            ],
            [
                'enunciado' => 'Qual tag é considerado obsoleta?',
                'opcao_a' => '<mark>',
                'opcao_b' => '<cite>',
                'opcao_c' => '<acronym>',
                'opcao_d' => '<code>',
                'resposta_correta' => 'opcao_c',
                'dificuldade' => 'Difícil',
            ],
            [
                'enunciado' => 'Qual maneira correta de conseguir pegar um elemento pela classe?',
                'opcao_a' => "window.document.getElementbyClass('element')",
                'opcao_b' => "window.document.querySelector('.element')",
                'opcao_c' => "window.document.getElementbyId('element')",
                'opcao_d' => "window.document.querySelector('#element')",
                'resposta_correta' => "opcao_b",
                'dificuldade' => 'Médio',
            ],
            [
                'enunciado' => 'Uma váriavel declarada como const, significa o quê?',
                'opcao_a' => 'Não pode ser atribuido outro valor a ela',
                'opcao_b' => 'Pode ser atribuido outro valor depois',
                'opcao_c' => 'Ela se torna uma arrow function obrigatoriamente',
                'opcao_d' => 'Pode receber outro valor somente em escopo local',
                'resposta_correta' => 'opcao_a',
                'dificuldade' => 'Fácil',
            ],
            [
                'enunciado' => 'Em javaScript, posso ver o resultado de 1+1 utilizando qual função?',
                'opcao_a' => 'echo()',
                'opcao_b' => 'printf()',
                'opcao_c' => 'setTimeout()',
                'opcao_d' => 'window.alert()',
                'resposta_correta' => 'opcao_d',
                'dificuldade' => 'Fácil',
            ],
            [
                'enunciado' => 'Em vue, v-show equivale a qual?',
                'opcao_a' => 'v-if',
                'opcao_b' => 'v-bind',
                'opcao_c' => '@click',
                'opcao_d' => 'v-for',
                'resposta_correta' => 'opcao_a',
                'dificuldade' => 'Difícil',
            ],



            [
                'enunciado' => 'Em PHP, qual tag é fundamental para o funcionamento do código em espoco global?',
                'opcao_a' => '<?php ?>',
                'opcao_b' => '<?= ?>',
                'opcao_c' => '<?php echo ?>',
                'opcao_d' => '<? ?>',
                'resposta_correta' => 'opcao_a',
                'dificuldade' => 'Fácil',
            ],
            [
                'enunciado' => 'Em PHP, quais funções retornam um número decimal arredondado, o valor absoluto de um número e um decimal arredondado para cima? ?',
                'opcao_a' => 'ceil(), asin(), round()',
                'opcao_b' => 'ceil(), round(), floor()',
                'opcao_c' => 'round(), abs(), ceil()',
                'opcao_d' => 'round(), max(), ctype_upper()',
                'resposta_correta' => 'opcao_c',
                'dificuldade' => 'Médio',
            ],
            [
                'enunciado' => 'Se eu quisesse essa frase concatenada em PHP, como ficaria?',
                'opcao_a' => '"Meu nome é %s e gosto de %s", $nome ,$acao',
                'opcao_b' => '"Meu nome é" . $nome . " e gosto de" . $acao',
                'opcao_c' => '"Meu nome é" + $nome + " e gosto de + $acao',
                'opcao_d' => 'f"Meu nome é {$nome} e gosto de {$acao}',
                'resposta_correta' => 'opcao_b',
                'dificuldade' => 'Médio',
            ],
            [
                'enunciado' => 'Em C, para eu declarar um array do tipo string, como seria?',
                'opcao_a' => 'string lista_nomes[3] = {"Maria", "José", "Jesus"}',
                'opcao_b' => 'char lista_nomes[3] = {"Maria", "José", "Jesus"}',
                'opcao_c' => 'string lista_nomes[10][3] = {"Maria", "José", "Jesus"}',
                'opcao_d' => 'char lista_nomes[10][3] = {"Maria", "José", "Jesus"}',
                'resposta_correta' => 'opcao_d',
                'dificuldade' => 'Difícil',
            ],
            [
                'enunciado' => 'Qual desses tipos primitivos não existe em C?',
                'opcao_a' => 'int',
                'opcao_b' => 'double',
                'opcao_c' => 'boolean',
                'opcao_d' => 'float',
                'resposta_correta' => 'opcao_c',
                'dificuldade' => 'Médio',
            ],
            [
                'enunciado' => 'Qual das linhas abaixo não apresenta erros na linguagem C?',
                'opcao_a' => 'int valor = "100";',
                'opcao_b' => 'double pi = 3,1415;',
                'opcao_c' => 'float numero = 7;',
                'opcao_d' => 'char nome[4] = "Zack";',
                'resposta_correta' => 'opcao_c',
                'dificuldade' => 'Médio',
            ],
            [
                'enunciado' => 'Em vue, o hook "onMounted" desempenha a função de:',
                'opcao_a' => 'montar um componente após uma ação reativa',
                'opcao_b' => 'registrar um função de callback para ser executada após o DOM ser carregado',
                'opcao_c' => 'execultar um comando a partir do estado de outra variável quando a mesma se satisfazer verdadeira',
                'opcao_d' => 'redirecionar para outra rota assim que o DOM é carregado',
                'resposta_correta' => 'opcao_b',
                'dificuldade' => 'Difícil',
            ],
            [
                'enunciado' => 'Qual das seguintes nomeclaturas pertence ao vue:',
                'opcao_a' => 'ref()',
                'opcao_b' => 'useEffect()',
                'opcao_c' => 'hash()',
                'opcao_d' => 'useContext()',
                'resposta_correta' => 'opcao_b',
                'dificuldade' => 'Médio',
            ],
            [
                'enunciado' => 'Qual diretiva é necessária para o envio de formulários em Blade?',
                'opcao_a' => '@yield',
                'opcao_b' => '@push',
                'opcao_c' => '@csrf',
                'opcao_d' => '@include',
                'resposta_correta' => 'opcao_c',
                'dificuldade' => 'Difícil',
            ],
            [
                'enunciado' => 'Com Laravel, como posso adicionar a coluna "profissao" na tabela "users"?',
                'opcao_a' => 'php artisan make:migration add_column_profissao_to_users_table --table-users',
                'opcao_b' => 'php artisan make:migration add_profissao_to_user_table --table-users',
                'opcao_c' => 'php artisan make:migration add_profissao_to_users_table',
                'opcao_d' => 'php artisan migrate:make add_profissao_to_users_table --table-users',
                'resposta_correta' => 'opcao_b',
                'dificuldade' => 'Difícil',
            ],

            
            [
                'enunciado' => 'Em JavaScript, qual método é utilizado para transformar uma string em um número inteiro?',
                'opcao_a' => 'Number()',
                'opcao_b' => 'parseInt()',
                'opcao_c' => 'parseFloat()',
                'opcao_d' => 'toInt()',
                'resposta_correta' => 'opcao_b',
                'dificuldade' => 'Fácil',
            ],
            [
                'enunciado' => 'Qual comando SQL é usado para atualizar registros existentes em uma tabela?',
                'opcao_a' => 'ALTER TABLE',
                'opcao_b' => 'UPDATE',
                'opcao_c' => 'INSERT INTO',
                'opcao_d' => 'REPLACE',
                'resposta_correta' => 'opcao_b',
                'dificuldade' => 'Fácil',
            ],
            [
                'enunciado' => 'Em PHP, qual função é utilizada para verificar se uma variável está definida e não é nula?',
                'opcao_a' => 'empty()',
                'opcao_b' => 'isset()',
                'opcao_c' => 'defined()',
                'opcao_d' => 'is_null()',
                'resposta_correta' => 'opcao_b',
                'dificuldade' => 'Médio',
            ],
            [
                'enunciado' => 'No Laravel, qual comando cria um novo controller com métodos RESTful básicos?',
                'opcao_a' => 'php artisan make:controller UserController --resource',
                'opcao_b' => 'php artisan create:controller UserController',
                'opcao_c' => 'php artisan controller:make UserController -r',
                'opcao_d' => 'php artisan make:resource UserController',
                'resposta_correta' => 'opcao_a',
                'dificuldade' => 'Difícil',
            ],
            [
                'enunciado' => 'Em C, qual operador é usado para acessar o valor apontado por um ponteiro?',
                'opcao_a' => '&',
                'opcao_b' => '*',
                'opcao_c' => '->',
                'opcao_d' => '%',
                'resposta_correta' => 'opcao_b',
                'dificuldade' => 'Difícil',
            ],
            [
                'enunciado' => 'Qual desses tipos pertence ao JavaScript?',
                'opcao_a' => 'double',
                'opcao_b' => 'char',
                'opcao_c' => 'undefined',
                'opcao_d' => 'byte',
                'resposta_correta' => 'opcao_c',
                'dificuldade' => 'Fácil',
            ],
            [
                'enunciado' => 'Em programação orientada a objetos, qual conceito representa a capacidade de um método ter comportamentos diferentes dependendo do contexto?',
                'opcao_a' => 'Herança',
                'opcao_b' => 'Encapsulamento',
                'opcao_c' => 'Polimorfismo',
                'opcao_d' => 'Abstração',
                'resposta_correta' => 'opcao_c',
                'dificuldade' => 'Médio',
            ],
            [
                'enunciado' => 'Sobre bancos de dados relacionais, qual afirmação está correta?',
                'opcao_a' => 'Uma primary key aceita valores duplicados',
                'opcao_b' => 'Uma foreign key sempre aponta para a primary key de outra tabela',
                'opcao_c' => 'Uma foreign key não permite valores nulos',
                'opcao_d' => 'Primary keys podem ser alteradas livremente a qualquer momento',
                'resposta_correta' => 'opcao_b',
                'dificuldade' => 'Difícil',
            ],
            [
                'enunciado' => 'No Vue.js, qual diretiva é usada para renderização condicional?',
                'opcao_a' => 'v-if',
                'opcao_b' => 'v-show',
                'opcao_c' => 'v-for',
                'opcao_d' => 'v-bind',
                'resposta_correta' => 'opcao_a',
                'dificuldade' => 'Fácil',
            ],
            [
                'enunciado' => 'No Laravel, qual método do Eloquent retorna todos os registros de uma tabela?',
                'opcao_a' => 'find()',
                'opcao_b' => 'get()',
                'opcao_c' => 'all()',
                'opcao_d' => 'first()',
                'resposta_correta' => 'opcao_c',
                'dificuldade' => 'Médio',
            ],



            [
                'enunciado' => 'Em Python, qual estrutura é utilizada para criar listas por compreensão?',
                'opcao_a' => '[x for x in lista]',
                'opcao_b' => '{x for x in lista}',
                'opcao_c' => '(x for x in lista)',
                'opcao_d' => '<x for x in lista>',
                'resposta_correta' => 'opcao_a',
                'dificuldade' => 'Médio',
            ],
            [
                'enunciado' => 'Qual palavra-chave define uma função em Python?',
                'opcao_a' => 'function',
                'opcao_b' => 'def',
                'opcao_c' => 'func',
                'opcao_d' => 'lambda',
                'resposta_correta' => 'opcao_b',
                'dificuldade' => 'Fácil',
            ],
            [
                'enunciado' => 'Em Java, qual modificador indica que um método pertence à classe e não à instância?',
                'opcao_a' => 'final',
                'opcao_b' => 'public',
                'opcao_c' => 'static',
                'opcao_d' => 'abstract',
                'resposta_correta' => 'opcao_c',
                'dificuldade' => 'Médio',
            ],
            [
                'enunciado' => 'Qual tipo primitivo em Java representa números inteiros de 64 bits?',
                'opcao_a' => 'short',
                'opcao_b' => 'long',
                'opcao_c' => 'double',
                'opcao_d' => 'byte',
                'resposta_correta' => 'opcao_b',
                'dificuldade' => 'Fácil',
            ],
            [
                'enunciado' => 'Em C++, qual símbolo é usado para acessar membros de um ponteiro para objeto?',
                'opcao_a' => '.',
                'opcao_b' => '->',
                'opcao_c' => '&',
                'opcao_d' => '::',
                'resposta_correta' => 'opcao_b',
                'dificuldade' => 'Médio',
            ],
            [
                'enunciado' => 'Qual das seguintes opções NÃO é um recurso exclusivo do C++?',
                'opcao_a' => 'Sobrecarga de operadores',
                'opcao_b' => 'Templates',
                'opcao_c' => 'Manipulação de ponteiros',
                'opcao_d' => 'Garbage Collector nativo',
                'resposta_correta' => 'opcao_d',
                'dificuldade' => 'Difícil',
            ],
            [
                'enunciado' => 'Em C#, qual palavra-chave cria um método assíncrono?',
                'opcao_a' => 'await',
                'opcao_b' => 'async',
                'opcao_c' => 'task',
                'opcao_d' => 'future',
                'resposta_correta' => 'opcao_b',
                'dificuldade' => 'Médio',
            ],
            [
                'enunciado' => 'Qual estrutura de coleção em C# garante que não existam elementos duplicados?',
                'opcao_a' => 'List',
                'opcao_b' => 'Dictionary',
                'opcao_c' => 'HashSet',
                'opcao_d' => 'Queue',
                'resposta_correta' => 'opcao_c',
                'dificuldade' => 'Médio',
            ],
            [
                'enunciado' => 'O que a função len() retorna em Python?',
                'opcao_a' => 'A quantidade de bytes de uma variável',
                'opcao_b' => 'O tamanho de um objeto iterável',
                'opcao_c' => 'O tipo de uma variável',
                'opcao_d' => 'O endereço de memória',
                'resposta_correta' => 'opcao_b',
                'dificuldade' => 'Fácil',
            ],
            [
                'enunciado' => 'Qual dessas opções representa corretamente um dicionário em Python?',
                'opcao_a' => '[ "nome" => "João" ]',
                'opcao_b' => '{ "nome": "João" }',
                'opcao_c' => '( "nome": "João" )',
                'opcao_d' => '< nome: João >',
                'resposta_correta' => 'opcao_b',
                'dificuldade' => 'Fácil',
            ],


            
            [
                'enunciado' => 'O que significa "polimorfismo" em Java?',
                'opcao_a' => 'Várias variáveis apontam para o mesmo objeto',
                'opcao_b' => 'Um método pode ter vários nomes',
                'opcao_c' => 'Um objeto pode assumir diferentes formas a partir da herança',
                'opcao_d' => 'Um atributo é sempre imutável',
                'resposta_correta' => 'opcao_c',
                'dificuldade' => 'Difícil',
            ],
            [
                'enunciado' => 'Qual coleção em Java mantém elementos ordenados automaticamente?',
                'opcao_a' => 'ArrayList',
                'opcao_b' => 'HashMap',
                'opcao_c' => 'TreeSet',
                'opcao_d' => 'LinkedList',
                'resposta_correta' => 'opcao_c',
                'dificuldade' => 'Médio',
            ],
            [
                'enunciado' => 'Qual palavra-chave impede que uma variável em C++ seja alterada?',
                'opcao_a' => 'let',
                'opcao_b' => 'lock',
                'opcao_c' => 'const',
                'opcao_d' => 'static',
                'resposta_correta' => 'opcao_c',
                'dificuldade' => 'Fácil',
            ],
            [
                'enunciado' => 'Em C++, qual tipo de dado é mais adequado para representar números muito grandes?',
                'opcao_a' => 'short',
                'opcao_b' => 'int',
                'opcao_c' => 'long long',
                'opcao_d' => 'float',
                'resposta_correta' => 'opcao_c',
                'dificuldade' => 'Médio',
            ],
            [
                'enunciado' => 'Qual estrutura permite percorrer coleções usando LINQ em C#?',
                'opcao_a' => 'IEnumerable',
                'opcao_b' => 'Array',
                'opcao_c' => 'List',
                'opcao_d' => 'Struct',
                'resposta_correta' => 'opcao_a',
                'dificuldade' => 'Difícil',
            ],
            [
                'enunciado' => 'Qual palavra-chave indica herança em C#?',
                'opcao_a' => 'extends',
                'opcao_b' => ':',
                'opcao_c' => 'inherits',
                'opcao_d' => 'super',
                'resposta_correta' => 'opcao_b',
                'dificuldade' => 'Fácil',
            ],
            [
                'enunciado' => 'Qual operador em Python compara identidade de objetos?',
                'opcao_a' => '==',
                'opcao_b' => '=',
                'opcao_c' => 'is',
                'opcao_d' => 'equals',
                'resposta_correta' => 'opcao_c',
                'dificuldade' => 'Difícil',
            ],
            [
                'enunciado' => 'O que significa PEP8 em Python?',
                'opcao_a' => 'Formato de compactação',
                'opcao_b' => 'Guia de boas práticas de código',
                'opcao_c' => 'Biblioteca padrão',
                'opcao_d' => 'Protocolo de rede',
                'resposta_correta' => 'opcao_b',
                'dificuldade' => 'Médio',
            ],
            [
                'enunciado' => 'Qual pacote padrão do Java contém a classe Scanner?',
                'opcao_a' => 'java.util',
                'opcao_b' => 'java.io',
                'opcao_c' => 'java.net',
                'opcao_d' => 'java.main',
                'resposta_correta' => 'opcao_a',
                'dificuldade' => 'Fácil',
            ],
            [
                'enunciado' => 'Qual palavra-chave impede que uma classe seja herdada em Java?',
                'opcao_a' => 'static',
                'opcao_b' => 'final',
                'opcao_c' => 'sealed',
                'opcao_d' => 'const',
                'resposta_correta' => 'opcao_b',
                'dificuldade' => 'Difícil',
            ],

        ]);
    }
}
